### ISSUE TITLE
The question about path of model

### ISSUE THREAD

**Issue by Common-Player** [SheezaShabbir/Time-series-Analysis-using-LSTM-RNN-and-GRU#1]
It is a amazing project thanks for you very much! but when I implements the code, I met a error I don't know how to solve. Its specific information is as follows:
OSError: [Errno 22] Invalid argument: 'RNNModel(\n  (rnn): RNN(56, 64, num_layers=3, batch_first=True, dropout=0.2)\n  (fc): Linear(in_features=64, out_features=1, bias=True)\n)_2022-09-16 09:59:58'
What should I do? Looking forward your reply! Thank you again!

**Comment by SheezaShabbir** [comment]
Can you share the screen short of your RNN model code?

**Comment by SheezaShabbir** [comment]
The code is working perfectly on my side.

**Comment by ConstBob** [comment]
I have met with the same trouble. I am trying to fix it.

**Comment by SheezaShabbir** [comment]
I hope the error is solved now. As my code is perfectly working from my side. Then I  should close this issue.

**Comment by ConstBob** [comment]
Hi,


Thank you for your email. It seems that it is working rightly now. Thank you for your attention to this issue.



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 17, 2023 19:36 PM
To: ***@***.***&gt;;
Cc: "Yiming ***@***.******@***.***&gt;;
Subject: Re: [SheezaShabbir/Time-series-Analysis-using-LSTM-RNN-and-GRU] Thequestion about path of model (Issue #1)




 
I hope the error is solved now. As my code is perfectly working from my side. Then I  should close this issue.

**Comment by SheezaShabbir** [comment]
Thank you for your work.
